version: '3.6'
services:
  minimal-packager:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.package
    volumes:
      - .:/app/build
  ci:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ci

  browser-maze-runner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.browser
      target: browser-maze-runner
      args:
        - BUILDKITE_BUILD_NUMBER
    environment:
      VERBOSE:
      DEBUG:
      BROWSER: "${BROWSER:-chrome_61}"
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_LOCAL_IDENTIFIER: ${BUILDKITE_JOB_ID:-maze-runner}
      HOST: "${HOST:-maze-runner}"
      API_HOST: "${API_HOST:-maze-runner}"
    networks:
      default:
        aliases:
          - maze-runner

  node-maze-runner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.node
      target: node-maze-runner
    environment:
      NODE_VERSION: "${NODE_VERSION:-10}"
      COMPOSE_PROJECT_NAME: "node${NODE_VERSION:-10}"
      NETWORK_NAME: "${BUILDKITE_JOB_ID:-js-maze-runner}"
      VERBOSE:
      DEBUG:
    networks:
      default:
        aliases:
          - maze-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  expo-maze-runner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.expo
      args:
        - BUILDKITE_BUILD_NUMBER
    environment:
      VERBOSE:
      DEBUG:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_LOCAL_IDENTIFIER: ${BUILDKITE_JOB_ID:-maze-runner}
      APP_LOCATION:
      DEVICE_TYPE:
    networks:
      default:
        aliases:
          - maze-runner
    volumes:
      - ./build:/app/test/expo/build

  expo-publisher:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.expo-publisher
    environment:
      EXPO_USERNAME:
      EXPO_PASSWORD:
      EXPO_RELEASE_CHANNEL:
    networks:
      default:
        aliases:
          - maze-runner

  expo-android-builder:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.expo-android-builder
    environment:
      VERBOSE:
      DEBUG:
      EXPO_USERNAME:
      EXPO_PASSWORD:
      EXPO_RELEASE_CHANNEL:
    networks:
      default:
        aliases:
          - maze-runner
    volumes:
      - ./build:/app/test/expo/features/fixtures/build

networks:
  default:
    name: ${BUILDKITE_JOB_ID:-js-maze-runner}
